kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: hHyN3oqfhMXNsxgwdOOkC8IEjxOJdOivE9Zae6CYeeM=
      - identity: {}
